//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//


package com.megatravel.dto.system_user_info;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.megatravel.dto.global_parameters.AddressDTO;
import com.megatravel.dto.global_parameters.RoleDTO;
import com.megatravel.dto.hotel.HotelDTO;
import com.megatravel.dto.room_reservation.RoomReservationDTO;
import com.megatravel.model.system_user_info.Role;
import com.megatravel.model.system_user_info.User;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.megatravel.com/global_parameters}Id"/>
 *         &lt;element name="First_name" type="{http://www.megatravel.com/global_parameters}Name"/>
 *         &lt;element name="Last_name" type="{http://www.megatravel.com/global_parameters}Name"/>
 *         &lt;element name="Username" type="{http://www.megatravel.com/global_parameters}Name"/>
 *         &lt;element name="Email" type="{http://www.megatravel.com/global_parameters}Email"/>
 *         &lt;element name="Active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Adress" type="{http://www.megatravel.com/global_parameters}AddressDTO"/>
 *         &lt;element name="Work_certificate_number" type="{http://www.megatravel.com/global_parameters}Work_certificate_number"/>
 *         &lt;element name="Role" type="{http://www.megatravel.com/global_parameters}RoleDTO" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.megatravel.com/hotel}HotelDTO"/>
 *         &lt;element ref="{http://www.megatravel.com/room_reservation}Room_reservationDTO" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "firstName",
    "lastName",
    "username",
    "email",
    "active",
    "adress",
    "workCertificateNumber",
    "role",
    "hotelDTO",
    "roomReservationDTO"
})
@XmlRootElement(name = "System_user_infoDTO")
public class SystemUserInfoDTO {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "First_name", required = true)
    protected String firstName;
    @XmlElement(name = "Last_name", required = true)
    protected String lastName;
    @XmlElement(name = "Username", required = true)
    protected String username;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "Active")
    protected boolean active;
    @XmlElement(name = "Adress", required = true)
    protected AddressDTO adress;
    @XmlElement(name = "Work_certificate_number", required = true)
    protected String workCertificateNumber;
    @XmlElement(name = "Role", required = true)
    protected List<RoleDTO> role;
    @XmlElement(name = "HotelDTO", namespace = "http://www.megatravel.com/hotel", required = true)
    protected HotelDTO hotelDTO;
    @XmlElement(name = "Room_reservationDTO", namespace = "http://www.megatravel.com/room_reservation", required = true)
    protected List<RoomReservationDTO> roomReservationDTO;

    
    public SystemUserInfoDTO() {
   	}

   	public SystemUserInfoDTO(User user) {
   		this.id = user.getId();
   		this.email = user.getEmail();
   		this.firstName = user.getName();
   		this.lastName = user.getLastName();
   		this.role = new ArrayList<>();
   		for (Role tempRole : user.getRoles()) {
   			this.role.add(new RoleDTO(tempRole));
   		}
   	}
    
    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the active property.
     * 
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the adress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDTO }
     *     
     */
    public AddressDTO getAdress() {
        return adress;
    }

    /**
     * Sets the value of the adress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDTO }
     *     
     */
    public void setAdress(AddressDTO value) {
        this.adress = value;
    }

    /**
     * Gets the value of the workCertificateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkCertificateNumber() {
        return workCertificateNumber;
    }

    /**
     * Sets the value of the workCertificateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkCertificateNumber(String value) {
        this.workCertificateNumber = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the role property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleDTO }
     * 
     * 
     */
    public List<RoleDTO> getRole() {
        if (role == null) {
            role = new ArrayList<RoleDTO>();
        }
        return this.role;
    }

    /**
     * Gets the value of the hotelDTO property.
     * 
     * @return
     *     possible object is
     *     {@link HotelDTO }
     *     
     */
    public HotelDTO getHotelDTO() {
        return hotelDTO;
    }

    /**
     * Sets the value of the hotelDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelDTO }
     *     
     */
    public void setHotelDTO(HotelDTO value) {
        this.hotelDTO = value;
    }

    /**
     * Gets the value of the roomReservationDTO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roomReservationDTO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoomReservationDTO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoomReservationDTO }
     * 
     * 
     */
    public List<RoomReservationDTO> getRoomReservationDTO() {
        if (roomReservationDTO == null) {
            roomReservationDTO = new ArrayList<RoomReservationDTO>();
        }
        return this.roomReservationDTO;
    }

}
