//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//


package com.megatravel.dto.hotel;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.megatravel.dto.global_parameters.CurrencyPriceDTO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.megatravel.com/global_parameters}Id"/>
 *         &lt;element name="Price" type="{http://www.megatravel.com/global_parameters}Currency_priceDTO"/>
 *         &lt;element name="Room" type="{http://www.megatravel.com/global_parameters}Id"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "price",
    "room",
    "lastChangedTime"
})
@XmlRootElement(name = "Unit_price_informationDTO")
public class UnitPriceInformationDTO {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "Price", required = true)
    protected CurrencyPriceDTO price;
    @XmlElement(name = "Room")
    protected long room;
    // TODO : Anotacija mozda?
    @XmlElement(name = "LastChangedTime")
    protected Date lastChangedTime;
    
    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyPriceDTO }
     *     
     */
    public CurrencyPriceDTO getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyPriceDTO }
     *     
     */
    public void setPrice(CurrencyPriceDTO value) {
        this.price = value;
    }

    /**
     * Gets the value of the room property.
     * 
     */
    public long getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     * 
     */
    public void setRoom(long value) {
        this.room = value;
    }

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

}
