//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//


package com.megatravel.dtosoap.hotel;

import java.util.Date;

import com.megatravel.dtosoap.global_parameters.CurrencyPriceDTO;

public class UnitPriceInformationDTO {

    protected long id;
    protected CurrencyPriceDTO price;
    protected long room;
    protected Date lastChangedTime;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyPriceDTO }
     *     
     */
    public CurrencyPriceDTO getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyPriceDTO }
     *     
     */
    public void setPrice(CurrencyPriceDTO value) {
        this.price = value;
    }

    /**
     * Gets the value of the room property.
     * 
     */
    public long getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     * 
     */
    public void setRoom(long value) {
        this.room = value;
    }

}
