//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 09:48:04 PM CEST 
//

package com.megatravel.model.system_user_info;

import java.util.Date;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import com.megatravel.model.hotel.Hotel;

@Entity
public class Chat {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;
	
	@Temporal(TemporalType.TIMESTAMP)
	@NotNull
	protected Date lastChangedTime;
	
	@ManyToOne()
	protected Hotel chatsHotel;
	
	@OneToMany(mappedBy = "chat")
	protected Set<Message> messages;

	public Chat() { }

	public Chat(com.megatravel.dto.system_user_info.ChatDTO chatDTO) {
		this.id = chatDTO.getId();
		this.lastChangedTime = chatDTO.getLastChangedTime();
	}
	
	public Chat(com.megatravel.dtosoap.system_user_info.ChatDTO chatDTO) {
		this.id = chatDTO.getId();
		this.lastChangedTime = chatDTO.getLastChangedTime();
	}

	public Chat(Long id, Hotel chatsHotel, Date lastChangedTime) {
		super();
		this.id = id;
		this.chatsHotel = chatsHotel;
		this.lastChangedTime = lastChangedTime;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Hotel getChatsHotel() {
		return chatsHotel;
	}

	public void setChatsHotel(Hotel chatsHotel) {
		this.chatsHotel = chatsHotel;
	}

	public Set<Message> getMessages() {
		return messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

}
