//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.01 at 06:25:46 PM CEST 
//


package com.megatravel.dtosoap.global_parameters;

import java.util.Date;

import com.megatravel.model.global_parameters.Address;

public class AddressDTO {
    protected String country;
    protected String city;
    protected String street;
    protected int streetNumber;
    protected double coordinateX;
    protected double coordinateY;
    protected long id;
    protected Date lastChangedTime;
    
    public AddressDTO() {
    	
    }
    
    public AddressDTO(Address address) {
    	this.id = address.getId();
    	this.country = address.getCountry();
    	this.city = address.getCity();
    	this.street = address.getStreet();
    	this.streetNumber = address.getStreetNumber();
    	this.coordinateX = address.getCoordinateX();
    	this.coordinateY = address.getCoordinateY();
    	this.lastChangedTime = address.getLastChangedTime();
    }
    
    public AddressDTO(com.megatravel.dtosoap.global_parameters.AddressDTO address) {
    	this.id = address.getId();
    	this.country = address.getCountry();
    	this.city = address.getCity();
    	this.street = address.getStreet();
    	this.streetNumber = address.getStreetNumber();
    	this.coordinateX = address.getCoordinateX();
    	this.coordinateY = address.getCoordinateY();
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the streetNumber property.
     * 
     */
    public int getStreetNumber() {
        return streetNumber;
    }

    /**
     * Sets the value of the streetNumber property.
     * 
     */
    public void setStreetNumber(int value) {
        this.streetNumber = value;
    }

    /**
     * Gets the value of the coordinateX property.
     * 
     */
    public double getCoordinateX() {
        return coordinateX;
    }

    /**
     * Sets the value of the coordinateX property.
     * 
     */
    public void setCoordinateX(double value) {
        this.coordinateX = value;
    }

    /**
     * Gets the value of the coordinateY property.
     * 
     */
    public double getCoordinateY() {
        return coordinateY;
    }

    /**
     * Sets the value of the coordinateY property.
     * 
     */
    public void setCoordinateY(double value) {
        this.coordinateY = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

    
}
