//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.01 at 06:35:06 PM CEST 
//


package com.megatravel.dtosoap.global_parameters;

import java.util.Date;

import com.megatravel.model.global_parameters.CurrencyPrice;

public class CurrencyPriceDTO {

    protected long id;
    protected AmountTypeDTO amountDTO;
    protected Date lastChangedTime;

    public CurrencyPriceDTO() { }

    public CurrencyPriceDTO(CurrencyPrice currencyPrice) {
    	this.id = currencyPrice.getId();
    	this.lastChangedTime = currencyPrice.getLastChangedTime();
    	this.amountDTO = currencyPrice.getAmount() != null ? new AmountTypeDTO(currencyPrice.getAmount()) : null;
    }
    
    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountTypeDTO }
     *     
     */
    public AmountTypeDTO getAmountDTO() {
        return amountDTO;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountTypeDTO }
     *     
     */
    public void setAmountDTO(AmountTypeDTO value) {
        this.amountDTO = value;
    }

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

    
}
