//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.01 at 06:25:46 PM CEST 
//


package com.megatravel.dtosoap.global_parameters;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.megatravel.model.system_user_info.Privilege;
import com.megatravel.model.system_user_info.Role;

public class PrivilegeDTO {

    protected long id;
    protected String name;
    protected Date lastChangedTime;
    protected List<RoleDTO> rolesDTO = new ArrayList<RoleDTO>();
    
    public PrivilegeDTO() { }

	public PrivilegeDTO(Privilege newPrivilege) {
    	this.id = newPrivilege.getId();
    	this.name = newPrivilege.getName();
    	this.lastChangedTime = newPrivilege.getLastChangedTime();
    	if(newPrivilege.getRoles() != null) {
    		for(Role current : newPrivilege.getRoles()) {
    			this.rolesDTO.add(new RoleDTO(current));
    		}
    	}
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public long getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(long value) {
		this.id = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

	public List<RoleDTO> getRolesDTO() {
		return rolesDTO;
	}

	public void setRolesDTO(List<RoleDTO> rolesDTO) {
		this.rolesDTO = rolesDTO;
	}

	
}