//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.01 at 06:25:46 PM CEST 
//


package com.megatravel.dtosoap.global_parameters;

import com.megatravel.model.system_user_info.Privilege;

public class PrivilegeDTO {

    protected long id;
    protected String name;

    public PrivilegeDTO() {
    	
	}

	public PrivilegeDTO(Privilege tempPrivilege) {
    	this.id = tempPrivilege.getId();
    	this.name = tempPrivilege.getName();
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public long getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(long value) {
		this.id = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}