//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.01 at 06:25:46 PM CEST 
//


package com.megatravel.dtosoap.global_parameters;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;

import com.megatravel.dtosoap.system_user_info.SystemUserInfoDTO;
import com.megatravel.model.system_user_info.Role;
import com.megatravel.model.system_user_info.User;


public class RoleDTO {

	protected long id;
	protected String roleName;
	protected Date lastChangedTime;
	protected Collection<SystemUserInfoDTO> usersDTO = new ArrayList<SystemUserInfoDTO>();
	
	public RoleDTO() { }

	public RoleDTO(Role newRole) {
		this.id = newRole.getId();
		this.roleName = newRole.getRoleName();
		this.lastChangedTime = newRole.getLastChangedTime();
		if(newRole.getUsers() != null) {
			for (User current: newRole.getUsers()) {
				this.usersDTO.add(new SystemUserInfoDTO(current));
			}
		}
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public long getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(long value) {
		this.id = value;
	}

	/**
	 * Gets the value of the roleName property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * Sets the value of the roleName property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setRoleName(String value) {
		this.roleName = value;
	}

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

	public Collection<SystemUserInfoDTO> getUsersDTO() {
		return usersDTO;
	}

}