//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//

package com.megatravel.model.global_parameters;

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.megatravel.dto.global_parameters.AmountTypeDTO;

@Entity
public class AmountType {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;
	protected BigDecimal price;
	protected String currency;

	public AmountType() {

	}

	public AmountType(AmountTypeDTO amountTypeDTO) {
		this.id = amountTypeDTO.getId();
		this.price = amountTypeDTO.getPrice();
		this.currency = amountTypeDTO.getCurrency();
	}

	public AmountType(Long id, BigDecimal price, String currency) {
		super();
		this.id = id;
		this.price = price;
		this.currency = currency;
	}

	public Long getId() {
		return id;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

}
