//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//

package com.megatravel.model.global_parameters;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

@Entity
public class AmountType {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;
	
	protected BigDecimal price;
	
	protected String currency;
	
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	private Date lastChangedTime;
	
	public AmountType() { }

	public AmountType(com.megatravel.dto.global_parameters.AmountTypeDTO amountTypeDTO) {
		super();
		this.id = amountTypeDTO.getId();
		this.price = amountTypeDTO.getPrice();
		this.currency = amountTypeDTO.getCurrency();
		this.lastChangedTime = amountTypeDTO.getLastChangedTime();
	}
	
	public AmountType(com.megatravel.dtosoap.global_parameters.AmountTypeDTO amountTypeDTO) {
		super();
		this.id = amountTypeDTO.getId();
		this.price = amountTypeDTO.getPrice();
		this.currency = amountTypeDTO.getCurrency();
		this.lastChangedTime = amountTypeDTO.getLastChangedTime();
	}

	public AmountType(Long id, BigDecimal price, String currency, Date lastChangedTime) {
		super();
		this.id = id;
		this.price = price;
		this.currency = currency;
		this.lastChangedTime = lastChangedTime;
	}

	public Long getId() {
		return id;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

}
