//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//

package com.megatravel.model.global_parameters;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import com.megatravel.dto.global_parameters.CurrencyPriceDTO;

@Entity
public class CurrencyPrice {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long id;
	@OneToOne()
	protected AmountType amount;
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	private Date lastChangedTime;

	public CurrencyPrice() {

	}

	public CurrencyPrice(CurrencyPriceDTO currencyPriceDTO) {
		this.id = currencyPriceDTO.getId();
		this.amount = currencyPriceDTO.getAmount() != null ? new AmountType(currencyPriceDTO.getAmount()) : null;
	}

	public CurrencyPrice(Long id, AmountType amount) {
		super();
		this.id = id;
		this.amount = amount;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public AmountType getAmount() {
		return amount;
	}

	public void setAmount(AmountType amount) {
		this.amount = amount;
	}

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

}
