//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 09:48:04 PM CEST 
//


package com.megatravel.dtosoap.system_user_info;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.megatravel.dtosoap.hotel.HotelDTO;
import com.megatravel.model.system_user_info.Chat;
import com.megatravel.model.system_user_info.Message;

public class ChatDTO {

    protected long id;
    protected HotelDTO hotelDTO;
    protected List<MessageDTO> messages;
    protected Date lastChangedTime;

    public ChatDTO() {
    	super();
    }
    
    public ChatDTO(Chat chat) {
    	HotelDTO hotelDTO = new HotelDTO(chat.getChatsHotel());
    	this.messages = new ArrayList<>();
    	this.hotelDTO = hotelDTO;
    	this.id = chat.getId();
    	this.lastChangedTime = chat.getLastChangedTime();
    	for(Message message : chat.getMessages())
			this.messages.add(new MessageDTO(message));
    }
    
    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the hotelDTO property.
     * 
     * @return
     *     possible object is
     *     {@link HotelDTO }
     *     
     */
    public HotelDTO getHotelDTO() {
        return hotelDTO;
    }

    /**
     * Sets the value of the hotelDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelDTO }
     *     
     */
    public void setHotelDTO(HotelDTO value) {
        this.hotelDTO = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageDTO }
     * 
     * 
     */
    public List<MessageDTO> getMessages() {
        if (messages == null) {
            messages = new ArrayList<MessageDTO>();
        }
        return this.messages;
    }

}
