//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 09:48:04 PM CEST 
//


package com.megatravel.dtosoap.system_user_info;

import java.util.Date;

import com.megatravel.model.system_user_info.Message;

public class MessageDTO {
	
    protected long id;
    protected String caption;
    protected String text;
    protected boolean opened;
    protected Date date;
    protected ChatDTO chatDTO;
    protected SystemUserInfoDTO senderDTO;
    protected SystemUserInfoDTO receiverDTO;
    protected Date lastChangedTime;

    public MessageDTO() { }
    
    public MessageDTO(Message message) {
    	this.id = message.getId();
    	this.caption = message.getCaption();
    	this.text = message.getText();
    	this.opened = message.isOpened();
    	this.date = message.getDate();
    	this.lastChangedTime = message.getLastChangedTime();
    	this.senderDTO = (message.getSender() == null) ? null : new SystemUserInfoDTO(message.getSender());
    	this.receiverDTO = (message.getReceiver() == null) ? null : new SystemUserInfoDTO(message.getReceiver());
    }
    
    
    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the opened property.
     * 
     */
    public boolean isOpened() {
        return opened;
    }

    /**
     * Sets the value of the opened property.
     * 
     */
    public void setOpened(boolean value) {
        this.opened = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(Date value) {
        this.date = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link SystemUserInfoDTO }
     *     
     */
    public SystemUserInfoDTO getSenderDTO() {
        return senderDTO;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemUserInfoDTO }
     *     
     */
    public void setSenderDTO(SystemUserInfoDTO value) {
        this.senderDTO = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link SystemUserInfoDTO }
     *     
     */
    public SystemUserInfoDTO getReceiverDTO() {
        return receiverDTO;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemUserInfoDTO }
     *     
     */
    public void setReceiverDTO(SystemUserInfoDTO value) {
        this.receiverDTO = value;
    }

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

	public ChatDTO getChatDTO() {
		return chatDTO;
	}

	public void setChatDTO(ChatDTO chat) {
		this.chatDTO = chat;
	}

    
}
