//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.01 at 06:25:46 PM CEST 
//


package com.megatravel.dto.global_parameters;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.dto.global_parameters package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NewElement_QNAME = new QName("http://www.megatravel.com/global_parameters", "newElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.dto.global_parameters
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressDTO }
     * 
     */
    public AddressDTO createAddressDTO() {
        return new AddressDTO();
    }

    /**
     * Create an instance of {@link CurrencyPriceDTO }
     * 
     */
    public CurrencyPriceDTO createCurrencyPriceDTO() {
        return new CurrencyPriceDTO();
    }

    /**
     * Create an instance of {@link RoleDTO }
     * 
     */
    public RoleDTO createRoleDTO() {
        return new RoleDTO();
    }

    /**
     * Create an instance of {@link AmountTypeDTO }
     * 
     */
    public AmountTypeDTO createAmountTypeDTO() {
        return new AmountTypeDTO();
    }

    /**
     * Create an instance of {@link PrivilegeDTO }
     * 
     */
    public PrivilegeDTO createPrivilegeDTO() {
        return new PrivilegeDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.megatravel.com/global_parameters", name = "newElement")
    public JAXBElement<Object> createNewElement(Object value) {
        return new JAXBElement<Object>(_NewElement_QNAME, Object.class, null, value);
    }

}
