//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//


package com.megatravel.dtosoap.hotel;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.megatravel.model.hotel.ExtraOption;
import com.megatravel.model.hotel.HotelExtraOption;

public class ExtraOptionDTO {

    protected long id;
    protected String name;
    protected Date lastChangedTime;
    protected List<HotelDTO> hotelsDTO = new ArrayList<HotelDTO>();
    
    public ExtraOptionDTO() { }

    public ExtraOptionDTO(ExtraOption option) {
    	this.id = option.getId();
    	this.name = option.getName();
    	this.lastChangedTime = option.getLastChangedTime();
    	if(option.getHotelExtraOptions() != null) {
    		for(HotelExtraOption hotelExtraOption : option.getHotelExtraOptions()) {
    			this.hotelsDTO.add(new HotelDTO(hotelExtraOption.getHotelExtraOption()));
    		}
    	}
	}

	/**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

    
}
