//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//


package com.megatravel.dtosoap.hotel;

import java.util.Date;

import com.megatravel.model.hotel.Image;

public class ImageDTO {

    protected long id;
    protected String filePath;
    protected Date lastChangedTime;
    protected RoomDTO roomDTO;
    protected HotelDTO hotelDTO;
    
    public ImageDTO() { }

    public ImageDTO(Image image) {
		this.id = image.getId();
		this.filePath = image.getFilePath();
		this.lastChangedTime = image.getLastChangedTime();
		this.roomDTO = (image.getRoomImage() == null) ? null : new RoomDTO(image.getRoomImage());
		this.hotelDTO = (image.getHotel() == null) ? null : new HotelDTO(image.getHotel());
	}

	/**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the filePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * Sets the value of the filePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilePath(String value) {
        this.filePath = value;
    }

	public Date getLastChangedTime() {
		return lastChangedTime;
	}

	public void setLastChangedTime(Date lastChangedTime) {
		this.lastChangedTime = lastChangedTime;
	}

	public RoomDTO getRoomDTO() {
		return roomDTO;
	}

	public void setRoomDTO(RoomDTO roomDTO) {
		this.roomDTO = roomDTO;
	}

	public HotelDTO getHotelDTO() {
		return hotelDTO;
	}

	public void setHotelDTO(HotelDTO hotelDTO) {
		this.hotelDTO = hotelDTO;
	}

    
}
