//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//


package com.megatravel.LoginAndRegistration.dto.global_parameters;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.megatravel.LoginAndRegistration.model.Privilege;
import com.megatravel.LoginAndRegistration.model.Role;


/**
 * <p>Java class for RoleDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoleDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.megatravel.com/global_parameters}Id"/>
 *         &lt;element name="role_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="privileges" type="{http://www.megatravel.com/global_parameters}PrivilegeDTO" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoleDTO", propOrder = {
    "id",
    "roleName",
    "privileges"
})
public class RoleDTO {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "role_name", required = true)
    protected String roleName;
    @XmlElement(required = true)
    protected List<PrivilegeDTO> privileges;
    
    public RoleDTO() {
    	
    }

    public RoleDTO(Role tempRole) {
		this.id = tempRole.getId();
		this.roleName = tempRole.getRoleName();
		this.privileges = new ArrayList<>();
		if(tempRole.getPrivileges() != null) {
			for (Privilege tempPrivilege: tempRole.getPrivileges()) {
				this.privileges.add(new PrivilegeDTO(tempPrivilege));
			}
		}
	}

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the roleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * Sets the value of the roleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleName(String value) {
        this.roleName = value;
    }

    /**
     * Gets the value of the privileges property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the privileges property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrivileges().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrivilegeDTO }
     * 
     * 
     */
    public List<PrivilegeDTO> getPrivileges() {
        if (privileges == null) {
            privileges = new ArrayList<PrivilegeDTO>();
        }
        return this.privileges;
    }

}
