//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//


package com.megatravel.dto.global_parameters;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vp.spring.mtb.dto.global_parameters package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vp.spring.mtb.dto.global_parameters
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressDTO }
     * 
     */
    public AddressDTO createAddressDTO() {
        return new AddressDTO();
    }

    /**
     * Create an instance of {@link CurrencyPriceDTO }
     * 
     */
    public CurrencyPriceDTO createCurrencyPriceDTO() {
        return new CurrencyPriceDTO();
    }

    /**
     * Create an instance of {@link RoleDTO }
     * 
     */
    public RoleDTO createRoleDTO() {
        return new RoleDTO();
    }

    /**
     * Create an instance of {@link AmountTypeDTO }
     * 
     */
    public AmountTypeDTO createAmountTypeDTO() {
        return new AmountTypeDTO();
    }

    /**
     * Create an instance of {@link PrivilegeDTO }
     * 
     */
    public PrivilegeDTO createPrivilegeDTO() {
        return new PrivilegeDTO();
    }

}
