//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 06:51:34 PM CEST 
//


package com.megatravel.dtosoap.room_reservation;

import java.math.BigDecimal;
import java.util.Date;

import com.megatravel.dtosoap.hotel.RoomDTO;
import com.megatravel.model.room_reservation.RoomReservation;


public class RoomReservationDTO {

    protected long id;
    protected Date beginDate;
    protected Date endDate;
    protected boolean realised;
    protected RoomDTO roomDTO;
    protected BigDecimal price;

    public RoomReservationDTO(){
    	super();
    }
    public RoomReservationDTO(RoomReservation reservation) {
    	this.id = reservation.getId();
    	this.beginDate = reservation.getBeginDate();
    	this.endDate = reservation.getEndDate();
    	this.realised = reservation.isRealised();
    	this.price = reservation.getPrice();
    	this.roomDTO = (reservation.getRoomReservation()==null)?null: new RoomDTO(reservation.getRoomReservation());
    }
    
    
    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the beginDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * Sets the value of the beginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeginDate(Date value) {
        this.beginDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(Date value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the realised property.
     * 
     */
    public boolean isRealised() {
        return realised;
    }

    /**
     * Sets the value of the realised property.
     * 
     */
    public void setRealised(boolean value) {
        this.realised = value;
    }

    /**
     * Gets the value of the roomDTO property.
     * 
     * @return
     *     possible object is
     *     {@link RoomDTO }
     *     
     */
    public RoomDTO getRoomDTO() {
        return roomDTO;
    }

    /**
     * Sets the value of the roomDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomDTO }
     *     
     */
    public void setRoomDTO(RoomDTO value) {
        this.roomDTO = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

}
